//! `Style` department.

pub mod documentation;
pub mod frozen_string_literal_comment;
pub mod guard_clause;
pub mod hash_syntax;
pub mod if_unless_modifier;
pub mod mutable_constant;
pub mod numeric_literals;
pub mod redundant_condition;
pub mod redundant_parentheses;
pub mod redundant_return;
pub mod sole_nested_conditional;
pub mod string_literals;
pub mod symbol_proc;
pub mod trailing_comma;
pub mod trailing_comma_in_arguments;
pub mod trailing_comma_in_array_literal;
pub mod trailing_comma_in_hash_literal;
pub mod word_array;
