//! `Rails` department.

pub mod active_record_override;
pub mod application_record;
pub mod create_table_with_timestamps;
pub mod duration_arithmetic;
pub mod link_to_blank;
pub mod redirect_back_or_to;
pub mod unique_validation_without_index;
pub mod freeze_time;
pub mod http_status_name_consistency;
pub mod presence;
pub mod to_s_with_argument;
pub mod application_controller;
pub mod application_record;
pub mod dangerous_column_names;
pub mod delegate_allow_blank;
pub mod has_and_belongs_to_many;
pub mod scope_args;
