[package]
name = "cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
description = "Command-line interface"

[[bin]]
name = "elysium"
path = "src/main.rs"

[dependencies]
ruby_source.workspace = true
ruby_ast.workspace = true
linter.workspace = true
rules.workspace = true
config.workspace = true
clap.workspace = true
ignore.workspace = true
globset.workspace = true
rayon.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
parking_lot.workspace = true

[lints]
workspace = true
