//! Generates `NodeKind` and the child-traversal dispatch from Prism's node
//! schema (the vendored `ruby-prism` crate's `config.json` for the
//! pinned version. Keeping the list generated means it cannot drift from
//! the node types the parser actually produces.

use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::Path;

use serde::Deserialize;

#[derive(Deserialize)]
struct Config {
    nodes: Vec<Node>,
}

#[derive(Deserialize)]
struct Node {
    name: String,
    #[serde(default)]
    fields: Vec<Field>,
}

#[derive(Deserialize)]
struct Field {
    name: String,
    #[serde(rename = "type")]
    ty: String,
    #[serde(default)]
    kind: Option<serde_json::Value>,
}

impl Field {
    /// Mirrors `ruby-prism`'s build script: a single concrete `kind` makes the
    /// accessor return the typed node struct instead of the generic `Node`.
    fn accessor_is_typed(&self) -> bool {
        match &self.kind {
            Some(serde_json::Value::String(k)) => {
                !matches!(k.as_str(), "non-void expression" | "pattern expression" | "Node")
            }
            _ => false,
        }
    }
}

fn snake_case(name: &str) -> String {
    let mut out = String::with_capacity(name.len() + 8);
    for (i, ch) in name.chars().enumerate() {
        if ch.is_ascii_uppercase() {
            if i > 0 {
                out.push('_');
            }
            out.push(ch.to_ascii_lowercase());
        } else {
            out.push(ch);
        }
    }
    out
}

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let config_path =
        Path::new(&manifest_dir).join("../../vendor/ruby-prism/vendor/prism-1.9.0/config.json");
    println!("cargo:rerun-if-changed={}", config_path.display());
    println!("cargo:rerun-if-changed=build.rs");

    let config: Config =
        serde_json::from_slice(&fs::read(&config_path).expect("read prism config.json"))
            .expect("parse prism config.json");

    let mut out = String::new();
    out.push_str("// @generated by build.rs from prism/config.json. Do not edit.\n\n");

    // NodeKind enum.
    out.push_str("/// Discriminant for every Prism node type.\n");
    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]\n");
    out.push_str("#[repr(u8)]\n");
    out.push_str("#[allow(missing_docs)]\n");
    out.push_str("pub enum NodeKind {\n");
    for (i, node) in config.nodes.iter().enumerate() {
        writeln!(out, "    {} = {i},", node.name).unwrap();
    }
    out.push_str("}\n\n");

    out.push_str("impl NodeKind {\n");
    writeln!(
        out,
        "    /// Number of node kinds.\n    pub const COUNT: usize = {};\n",
        config.nodes.len()
    )
    .unwrap();
    out.push_str("    /// Every kind, in discriminant order.\n");
    out.push_str("    pub const ALL: [NodeKind; Self::COUNT] = [\n");
    for node in &config.nodes {
        writeln!(out, "        NodeKind::{},", node.name).unwrap();
    }
    out.push_str("    ];\n\n");

    out.push_str("    /// Prism's name for the node type, e.g. `CallNode`.\n");
    out.push_str("    pub const fn prism_name(self) -> &'static str {\n        match self {\n");
    for node in &config.nodes {
        writeln!(out, "            NodeKind::{} => \"{}\",", node.name, node.name).unwrap();
    }
    out.push_str("        }\n    }\n\n");

    out.push_str("    /// Looks a kind up by its Prism name.\n");
    out.push_str(
        "    pub fn from_prism_name(name: &str) -> Option<Self> {\n        match name {\n",
    );
    for node in &config.nodes {
        writeln!(out, "            \"{}\" => Some(NodeKind::{}),", node.name, node.name).unwrap();
    }
    out.push_str("            _ => None,\n        }\n    }\n\n");

    out.push_str("    /// True when the node type can never have child nodes.\n");
    out.push_str("    pub const fn is_leaf(self) -> bool {\n        matches!(self, ");
    let leaves: Vec<String> = config
        .nodes
        .iter()
        .filter(|n| !n.fields.iter().any(|f| matches!(f.ty.as_str(), "node" | "node?" | "node[]")))
        .map(|n| format!("NodeKind::{}", n.name))
        .collect();
    out.push_str(&leaves.join(" | "));
    out.push_str(")\n    }\n");
    out.push_str("}\n\n");

    // kind_of
    out.push_str("/// Returns the [`NodeKind`] of a Prism node.\n");
    out.push_str("pub fn kind_of(node: &Node<'_>) -> NodeKind {\n    match node {\n");
    for node in &config.nodes {
        writeln!(out, "        Node::{} {{ .. }} => NodeKind::{},", node.name, node.name).unwrap();
    }
    out.push_str("    }\n}\n\n");

    write_visit_children(&mut out, &config);

    let out_dir = env::var("OUT_DIR").unwrap();
    fs::write(Path::new(&out_dir).join("node_kind.rs"), out).expect("write node_kind.rs");
}

fn write_visit_children(out: &mut String, config: &Config) {
    out.push_str(
        "/// Visits every direct child of `node` through `visitor.visit`, so enter/leave\n",
    );
    out.push_str(
        "/// hooks fire for each node exactly once. Prism's own default traversal calls\n",
    );
    out.push_str("/// typed `visit_*_node` methods for single-kind fields and would skip them.\n");
    out.push_str("pub fn visit_children<'pr, V>(visitor: &mut V, node: &Node<'pr>)\nwhere\n    V: Visit<'pr> + ?Sized,\n{\n    match node {\n");
    for node in &config.nodes {
        let snake = snake_case(&node.name);
        let children: Vec<&Field> = node
            .fields
            .iter()
            .filter(|f| matches!(f.ty.as_str(), "node" | "node?" | "node[]"))
            .collect();
        if children.is_empty() {
            writeln!(out, "        Node::{} {{ .. }} => {{}}", node.name).unwrap();
            continue;
        }
        writeln!(out, "        Node::{} {{ .. }} => {{", node.name).unwrap();
        writeln!(out, "            let n = node.as_{snake}().expect(\"kind matched\");").unwrap();
        for f in children {
            let as_node = if f.accessor_is_typed() { ".as_node()" } else { "" };
            match f.ty.as_str() {
                "node" => {
                    writeln!(out, "            visitor.visit(&n.{}(){as_node});", f.name).unwrap();
                }
                "node?" => writeln!(
                    out,
                    "            if let Some(c) = n.{}() {{ visitor.visit(&c{as_node}); }}",
                    f.name
                )
                .unwrap(),
                _ => writeln!(out, "            for c in &n.{}() {{ visitor.visit(&c); }}", f.name)
                    .unwrap(),
            }
        }
        out.push_str("        }\n");
    }
    out.push_str("    }\n}\n");
}
